# 通过 ACME 申请 Let's Encrypt 证书

name: ACME
on:  
  # 手动触发
  workflow_dispatch:
env:
  ACME_ACCOUNT_EMAIL: acme@acme.cc
  ACME_ACCOUNT_KEY_LENGTH: 4096
  ACME_CONFIGURATION: CF_Email=123
  ACME_DAYS: 60
  ACME_DNS: dns_cf
  ACME_DNS_SLEEP: 30
  ACME_RSA_KEY_LENGTH: 4096
  ACME_DOMAIN: acme.cc
jobs:
  ACME:
    runs-on: ubuntu-latest
    steps:
      - name: '检出 acmesh-official/acme.sh 仓库'      
        uses: actions/checkout@v2
        with:
          repository: acmesh-official/acme.sh
          path: acme.sh
          submodules: true
      - name: '安装 acme.sh 脚本'
        run: |
          cd ${GITHUB_WORKSPACE}/acme.sh
          ./acme.sh --install --no-color --nocron --noprofile --accountemail ${ACME_ACCOUNT_EMAIL} --accountkeylength ${ACME_ACCOUNT_KEY_LENGTH}
          cd ${GITHUB_WORKSPACE}
          echo "${HOME}/.acme.sh" >> ${GITHUB_PATH}
      - name: '检查 acme.sh 版本'
        run: acme.sh --version
      - name: '设定 acme.sh 配置'
        run: echo "${ACME_EXPORTS}" >> ${GITHUB_ENV}
      - name: '检出仓库'
        uses: actions/checkout@v2
        with:
          path: acme
          submodules: true
      - name: '执行清理'
        run: |
          ls
          cd ${GITHUB_WORKSPACE}/acme
          ls
          rm --force --recursive ${GITHUB_WORKSPACE}/acme/${ACME_DOMAIN}/
          ls
          mkdir --parents ${GITHUB_WORKSPACE}/acme/${ACME_DOMAIN}
          ls
          cd ${GITHUB_WORKSPACE}/acme/${ACME_DOMAIN}
          ls
          cd ${GITHUB_WORKSPACE}
          ls
      
      
        
        
      
