# 通过 ACME 申请 Let's Encrypt 证书

name: ACME
on:  
  # 手动触发
  workflow_dispatch:
env:
  ACME_ACCOUNT_EMAIL: test@test.com
  ACME_ACCOUNT_KEY_LENGTH: 4096
  ACME_CONFIGURATION: CF_Email=123
jobs:
  ACME:
    runs-on: ubuntu-latest
    steps:
      - name: '检出 acmesh-official/acme.sh 仓库'      
        uses: actions/checkout@v2
        with:
          repository: acmesh-official/acme.sh
          path: acme.sh
          submodules: true
      - name: '安装 acme.sh 脚本'
        run: |
          cd ${GITHUB_WORKSPACE}/acme.sh
          ./acme.sh --install --no-color --nocron --noprofile --accountemail ${ACME_ACCOUNT_EMAIL} --accountkeylength ${ACME_ACCOUNT_KEY_LENGTH}
          cd ${GITHUB_WORKSPACE}
          echo "${HOME}/.acme.sh" >> ${GITHUB_PATH}
      - name: '检查 acme.sh 版本'
        run: acme.sh --version
      - name: '设定 acme.sh 配置 '
        run: echo "${ACME_EXPORTS}" >> ${GITHUB_ENV}
      - name: 测试 Git 
        run: git version
        
      
