# 通过 ACME 申请 Let's Encrypt 证书

name: ACME
on:  
  # 手动触发
  workflow_dispatch:
jobs:
  acme:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_WORKFLOW}
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_REF}
          echo ${GITHUB_BASE_REF}
          echo ${GITHUB_ACTION}
